
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // PENTING: ini WAJIB DIRECT_URL (session pooler, port 5432), bukan
  // DATABASE_URL. prisma.config.ts inilah yang benar-benar dipakai CLI untuk
  // migrate/db push — directUrl di schema.prisma tidak lagi berlaku begitu
  // file ini ada. Kalau diisi DATABASE_URL (transaction pooler, 6543),
  // migrasi akan bentrok prepared statement ("s1/s0 already exists").
  // schema.prisma tetap pakai DATABASE_URL untuk koneksi aplikasi saat runtime.
  datasource: {
    url: process.env.DIRECT_URL || "postgresql://dummy:5432/dummy",
  },
});
